Repository Manta-Network/Manta, pull requests merged in 2022-05, with the labels that each got.

#505 Proper bare-metal instances for benchmarking workflows
  .github/workflows/generate_calamari_weights_files.yml
  .github/workflows/generate_dolphin_weights_files.yml
  .github/workflows/generate_manta_weights_files.yml
  runtime/calamari/src/weights/calamari_vesting.rs
  runtime/calamari/src/weights/frame_system.rs
  runtime/calamari/src/weights/manta_collator_selection.rs
  runtime/calamari/src/weights/pallet_asset_manager.rs
  runtime/calamari/src/weights/pallet_assets.rs
  runtime/calamari/src/weights/pallet_balances.rs
  runtime/calamari/src/weights/pallet_collective.rs
  runtime/calamari/src/weights/pallet_democracy.rs
  runtime/calamari/src/weights/pallet_membership.rs
  runtime/calamari/src/weights/pallet_multisig.rs
  runtime/calamari/src/weights/pallet_preimage.rs
  runtime/calamari/src/weights/pallet_scheduler.rs
  runtime/calamari/src/weights/pallet_session.rs
  runtime/calamari/src/weights/pallet_timestamp.rs
  runtime/calamari/src/weights/pallet_treasury.rs
  runtime/calamari/src/weights/pallet_tx_pause.rs
  runtime/calamari/src/weights/pallet_utility.rs
  runtime/dolphin/src/weights/frame_system.rs
  runtime/dolphin/src/weights/manta_collator_selection.rs
  runtime/dolphin/src/weights/pallet_asset_manager.rs
  runtime/dolphin/src/weights/pallet_assets.rs
  runtime/dolphin/src/weights/pallet_balances.rs
  runtime/dolphin/src/weights/pallet_collective.rs
  runtime/dolphin/src/weights/pallet_democracy.rs
  runtime/dolphin/src/weights/pallet_manta_pay.rs
  runtime/dolphin/src/weights/pallet_membership.rs
  runtime/dolphin/src/weights/pallet_multisig.rs
  runtime/dolphin/src/weights/pallet_preimage.rs
  runtime/dolphin/src/weights/pallet_scheduler.rs
  runtime/dolphin/src/weights/pallet_session.rs
  runtime/dolphin/src/weights/pallet_timestamp.rs
  runtime/dolphin/src/weights/pallet_treasury.rs
  runtime/dolphin/src/weights/pallet_tx_pause.rs
  runtime/dolphin/src/weights/pallet_utility.rs
Labels: Weights, CI/CD

#541 Skip build on too tiny change
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: CI/CD

#539 Let CI support cargo audit and dependabot
  .github/ISSUE_TEMPLATE/release.md
  .github/dependabot.yml
  .github/workflows/audit.yml
Labels: CI/CD

#560 Bump srtool to v0.4.0
  .github/workflows/publish-draft-releases.yml
Labels: CI/CD

#550 Remove sudo pallet from calamari runtime
  Cargo.lock
  node/src/chain_specs/calamari.rs
  pallets/collator-selection/src/lib.rs
  runtime/calamari/Cargo.toml
  runtime/calamari/src/lib.rs
  runtime/calamari/src/migrations/mod.rs
  runtime/calamari/src/migrations/sudo.rs
  runtime/calamari/tests/integration_tests.rs
Labels: Calamari, Governance
