Repository Manta-Network/Manta, pull requests merged in 2022-06, with the labels that each got.

#554 Benchmark `cumulus-pallet-xcmp-queue` and white list `Treasury Account` in benchmark test
  .github/workflows/generate_calamari_weights_files.yml
  .github/workflows/generate_dolphin_weights_files.yml
  Cargo.lock
  runtime/calamari/Cargo.toml
  runtime/calamari/src/lib.rs
  runtime/calamari/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/calamari/src/weights/mod.rs
  runtime/calamari/src/xcm_config.rs
  runtime/dolphin/Cargo.toml
  runtime/dolphin/src/lib.rs
  runtime/dolphin/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/dolphin/src/weights/mod.rs
  runtime/dolphin/src/xcm_config.rs
  runtime/manta/src/lib.rs
Labels: CI/CD

#572 Release v3.2.0
  CHANGELOG.md
  Cargo.lock
  node/Cargo.toml
  node/src/chain_specs/dolphin.rs
  pallets/asset-manager/Cargo.toml
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/tests.rs
  pallets/collator-selection/Cargo.toml
  pallets/manta-pay/src/rpc.rs
  pallets/tx-pause/Cargo.toml
  pallets/vesting/Cargo.toml
  primitives/Cargo.toml
  runtime/calamari/Cargo.toml
  runtime/calamari/src/lib.rs
  runtime/calamari/src/migrations/sudo.rs
  runtime/calamari/src/weights/calamari_vesting.rs
  runtime/calamari/src/weights/frame_system.rs
  runtime/calamari/src/weights/manta_collator_selection.rs
  runtime/calamari/src/weights/pallet_asset_manager.rs
  runtime/calamari/src/weights/pallet_assets.rs
  runtime/calamari/src/weights/pallet_balances.rs
  runtime/calamari/src/weights/pallet_collective.rs
  runtime/calamari/src/weights/pallet_democracy.rs
  runtime/calamari/src/weights/pallet_membership.rs
  runtime/calamari/src/weights/pallet_multisig.rs
  runtime/calamari/src/weights/pallet_preimage.rs
  runtime/calamari/src/weights/pallet_scheduler.rs
  runtime/calamari/src/weights/pallet_session.rs
  runtime/calamari/src/weights/pallet_timestamp.rs
  runtime/calamari/src/weights/pallet_treasury.rs
  runtime/calamari/src/weights/pallet_tx_pause.rs
  runtime/calamari/src/weights/pallet_utility.rs
  runtime/common/Cargo.toml
  runtime/dolphin/Cargo.toml
  runtime/dolphin/src/lib.rs
  runtime/dolphin/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/dolphin/src/weights/frame_system.rs
  runtime/dolphin/src/weights/manta_collator_selection.rs
  runtime/dolphin/src/weights/pallet_asset_manager.rs
  runtime/dolphin/src/weights/pallet_assets.rs
  runtime/dolphin/src/weights/pallet_balances.rs
  runtime/dolphin/src/weights/pallet_collective.rs
  runtime/dolphin/src/weights/pallet_democracy.rs
  runtime/dolphin/src/weights/pallet_manta_pay.rs
  runtime/dolphin/src/weights/pallet_membership.rs
  runtime/dolphin/src/weights/pallet_multisig.rs
  runtime/dolphin/src/weights/pallet_preimage.rs
  runtime/dolphin/src/weights/pallet_scheduler.rs
  runtime/dolphin/src/weights/pallet_session.rs
  runtime/dolphin/src/weights/pallet_timestamp.rs
  runtime/dolphin/src/weights/pallet_treasury.rs
  runtime/dolphin/src/weights/pallet_tx_pause.rs
  runtime/dolphin/src/weights/pallet_utility.rs
  runtime/manta/Cargo.toml
  runtime/manta/src/lib.rs
Labels: Weights, Calamari, Runtime, Priority: High, xcm, Dolphin

#591 Mention SDK in release template
  .github/ISSUE_TEMPLATE/release.md
Labels: documentation

#449 [manta]Add strip profile to production
  .github/workflows/publish_draft_releases.yml
  CHANGELOG.md
  Cargo.toml
  README.md
  node/Cargo.toml
Labels: Manta, CI/CD

#634 Fixup to #601
  .github/workflows/Adam Reif
Labels: CI/CD

#563 Reimplement `TransactAsset` with `FungibleLedger` and `AssetConfig` traits
  CHANGELOG.md
  pallets/asset-manager/src/tests.rs
  pallets/manta-pay/src/lib.rs
  pallets/manta-pay/src/test/payment.rs
  primitives/src/assets.rs
  primitives/src/xcm.rs
  runtime/calamari/src/xcm_config.rs
  runtime/calamari/tests/integration_tests.rs
  runtime/common/tests/xcm_mock/mod.rs
  runtime/common/tests/xcm_mock/parachain.rs
  runtime/common/tests/xcm_tests.rs
  runtime/dolphin/src/xcm_config.rs
Labels: xcm
