Repository Manta-Network/Manta, pull requests merged in 2022-08, with the labels that each got.

#701 switch runtime to wasm only
  .gitignore
  node/src/command.rs
  node/src/service.rs
Labels: C-enhancement, A-runtime, P-medium, L-changed

#720 Update deps from v0.9.22 to v0.9.26
  .github/resources/config-for-integration-test.json
  .github/resources/config-for-runtime-upgrade-test.json
  Cargo.lock
  node/Cargo.toml
  node/src/cli.rs
  node/src/command.rs
  node/src/rpc/common.rs
  node/src/rpc/dolphin.rs
  node/src/service.rs
  pallets/asset-manager/Cargo.toml
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/tests.rs
  pallets/collator-selection/Cargo.toml
  pallets/collator-selection/src/lib.rs
  pallets/collator-selection/src/migrations.rs
  pallets/manta-pay/Cargo.toml
  pallets/manta-pay/src/lib.rs
  pallets/tx-pause/Cargo.toml
  pallets/tx-pause/src/lib.rs
  pallets/vesting/Cargo.toml
  pallets/vesting/src/lib.rs
  pallets/vesting/src/mock.rs
  pallets/vesting/src/tests.rs
  primitives/manta/Cargo.toml
  primitives/session-keys/Cargo.toml
  runtime/calamari/Cargo.toml
  runtime/calamari/src/fee.rs
  runtime/calamari/src/lib.rs
  runtime/calamari/src/migrations/sudo.rs
  runtime/calamari/src/weights/pallet_treasury.rs
  runtime/calamari/src/xcm_config.rs
  runtime/calamari/tests/integration_tests.rs
  runtime/common/Cargo.toml
  runtime/common/tests/xcm_mock/mod.rs
  runtime/common/tests/xcm_mock/parachain.rs
  runtime/common/tests/xcm_tests.rs
  runtime/dolphin/Cargo.toml
  runtime/dolphin/src/lib.rs
  runtime/dolphin/src/weights/pallet_treasury.rs
  runtime/dolphin/src/xcm_config.rs
  runtime/manta/Cargo.toml
  runtime/manta/src/lib.rs
Labels: C-enhancement, A-runtime, L-added, L-changed

#726 support STORAGE_VERSION for our pallets
  pallets/asset-manager/src/lib.rs
  pallets/manta-pay/src/lib.rs
  pallets/tx-pause/src/lib.rs
  pallets/vesting/src/lib.rs
  runtime/calamari/Cargo.toml
  runtime/calamari/src/lib.rs
  runtime/common/Cargo.toml
  runtime/common/src/lib.rs
  runtime/common/src/migration.rs
  runtime/dolphin/src/lib.rs
Labels: C-enhancement, A-runtime, L-changed

#738 Add changelog verification. Remove old changelog workflow
  .github/workflows/changelog_verification.yml
  .github/workflows/publish_draft_releases.yml
Labels: C-enhancement, A-ci, L-changed

#737 Remove v3.2.1 SessionKey migration code
  runtime/calamari/src/lib.rs
  runtime/dolphin/src/lib.rs
Labels: A-calamari, P-high, A-dolphin, C-cleanup, A-migration, L-removed

#712 Add RPC for latest checkpoint
  pallets/manta-pay/src/lib.rs
  pallets/manta-pay/src/rpc.rs
  pallets/manta-pay/src/types.rs
  runtime/dolphin/src/lib.rs
  tests/types.ts
Labels: C-enhancement, L-added, A-client

#752 v3.3.0 bump versions and weights
  .github/workflows/metadata_diff.yml
  .github/workflows/publish_draft_releases.yml
  Cargo.lock
  node/Cargo.toml
  pallets/asset-manager/Cargo.toml
  pallets/collator-selection/Cargo.toml
  pallets/tx-pause/Cargo.toml
  pallets/vesting/Cargo.toml
  primitives/manta/Cargo.toml
  primitives/session-keys/Cargo.toml
  runtime/calamari/Cargo.toml
  runtime/calamari/src/lib.rs
  runtime/calamari/src/weights/calamari_vesting.rs
  runtime/calamari/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/calamari/src/weights/frame_system.rs
  runtime/calamari/src/weights/manta_collator_selection.rs
  runtime/calamari/src/weights/pallet_asset_manager.rs
  runtime/calamari/src/weights/pallet_assets.rs
  runtime/calamari/src/weights/pallet_author_inherent.rs
  runtime/calamari/src/weights/pallet_balances.rs
  runtime/calamari/src/weights/pallet_collective.rs
  runtime/calamari/src/weights/pallet_democracy.rs
  runtime/calamari/src/weights/pallet_membership.rs
  runtime/calamari/src/weights/pallet_multisig.rs
  runtime/calamari/src/weights/pallet_preimage.rs
  runtime/calamari/src/weights/pallet_scheduler.rs
  runtime/calamari/src/weights/pallet_session.rs
  runtime/calamari/src/weights/pallet_timestamp.rs
  runtime/calamari/src/weights/pallet_treasury.rs
  runtime/calamari/src/weights/pallet_tx_pause.rs
  runtime/calamari/src/weights/pallet_utility.rs
  runtime/common/Cargo.toml
  runtime/dolphin/Cargo.toml
  runtime/dolphin/src/lib.rs
  runtime/dolphin/src/weights/cumulus_pallet_xcmp_queue.rs
  runtime/dolphin/src/weights/frame_system.rs
  runtime/dolphin/src/weights/manta_collator_selection.rs
  runtime/dolphin/src/weights/pallet_asset_manager.rs
  runtime/dolphin/src/weights/pallet_assets.rs
  runtime/dolphin/src/weights/pallet_author_inherent.rs
  runtime/dolphin/src/weights/pallet_balances.rs
  runtime/dolphin/src/weights/pallet_collective.rs
  runtime/dolphin/src/weights/pallet_democracy.rs
  runtime/dolphin/src/weights/pallet_manta_pay.rs
  runtime/dolphin/src/weights/pallet_membership.rs
  runtime/dolphin/src/weights/pallet_multisig.rs
  runtime/dolphin/src/weights/pallet_preimage.rs
  runtime/dolphin/src/weights/pallet_scheduler.rs
  runtime/dolphin/src/weights/pallet_session.rs
  runtime/dolphin/src/weights/pallet_timestamp.rs
  runtime/dolphin/src/weights/pallet_treasury.rs
  runtime/dolphin/src/weights/pallet_tx_pause.rs
  runtime/dolphin/src/weights/pallet_utility.rs
  runtime/manta/Cargo.toml
  runtime/manta/src/lib.rs
Labels: A-weights, L-release

#763 Support verification of historic Aura blocks
  Cargo.lock
  node/Cargo.toml
  node/src/aura_or_nimbus_consensus.rs
  node/src/lib.rs
  node/src/service.rs
Labels: C-enhancement, A-automation, L-added

#764 Release v3.3.0
  .github/workflows/publish_draft_releases.yml
  CHANGELOG.md
  Cargo.lock
  node/src/aura_or_nimbus_consensus.rs
  runtime/calamari/src/lib.rs
  runtime/dolphin/src/lib.rs
Labels: C-enhancement, L-release

#745 Workflow to check for labels
  .github/workflows/label_checker.yml
Labels: C-enhancement, A-ci, L-added

#770 Update fees splits, 50% burned, 50% to treasury
  .github/workflows/label_checker.yml
  runtime/calamari/src/fee.rs
  runtime/calamari/src/impls.rs
  runtime/calamari/tests/integration_tests.rs
  runtime/dolphin/src/impls.rs
Labels: A-collator-program, A-consensus, L-changed

#758 All-benchmarks script and CI workflow improvements
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/generate_calamari_weights_files.yml
  .github/workflows/generate_dolphin_weights_files.yml
  .github/workflows/metadata_diff.yml
  .github/workflows/publish_draft_releases.yml
  .github/workflows/run_all_benchmarks.yml
  .gitignore
  scripts/benchmarking/run_all_benchmarks.sh
Labels: C-enhancement, A-ci, L-added

#766 Change QA workflow link to internal Notion
  .github/ISSUE_TEMPLATE/release.md
  .github/workflows/label_checker.yml
Labels: C-enhancement, A-development, L-changed

#743 Split all testing from `publish_draft_release` workflow and filter execution by labels on the PRs
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check_tests.yml
  .github/workflows/docker.yml
  .github/workflows/integration_test_calamari.yml
  .github/workflows/integration_test_dolphin.yml
  .github/workflows/publish_draft_releases.yml
  .github/workflows/run_linters.yml
  .github/workflows/runtime_upgrade_test.yml
  .github/workflows/try-runtime-calamari-mainnet.yml
Labels: A-calamari, A-ci, A-dolphin, C-cleanup, L-changed
