Repository Manta-Network/Manta, pull requests merged in 2022-04, with the labels that each got.

#454 Fix potential expect() panic in runtime code, two xcm must-fail tests, and filter out unneeded XTokens extrinsics
  Cargo.lock
  primitives/src/xcm.rs
  runtime/dolphin/src/lib.rs
  runtime/dolphin/tests/xcm_tests.rs
Labels: xcm

#476 Set the version of feature resolver as `2`
  Cargo.toml
  pallets/manta-pay/Cargo.toml
Labels: enhancement

#461 Fix AssetManager's update_asset_metadata
  .github/workflows/generate_dolphin_weights_files.yml
  pallets/asset-manager/src/benchmarking.rs
  pallets/asset-manager/src/lib.rs
  pallets/asset-manager/src/tests.rs
  pallets/asset-manager/src/weights.rs
Labels: xcm

#473 Calamari XCM
  .github/workflows/check_tests.yml
  Cargo.lock
  primitives/src/xcm.rs
  runtime/calamari/Cargo.toml
  runtime/calamari/src/lib.rs
  runtime/calamari/tests/xcm_mock/mod.rs
  runtime/calamari/tests/xcm_mock/parachain.rs
  runtime/calamari/tests/xcm_mock/relay_chain.rs
  runtime/calamari/tests/xcm_tests.rs
  runtime/dolphin/src/lib.rs
Labels: xcm

#475 Workflow to check whether `transaction_version` should be bumped
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/metadata_diff.yml
  scripts/github/extrinsic-ordering-filter.sh
Labels: CI/CD, Runtime
