Repository Manta-Network/Manta, pull requests merged in 2022-03, with the labels that each got.

#411 Add a corner case for collator-selection
  CHANGELOG.md
  pallets/collator-selection/src/tests.rs
Labels: Calamari, Priority: Medium

#402 [manta] Substrate integration tests
  Cargo.lock
  node/src/chain_specs/calamari.rs
  node/src/chain_specs/dolphin.rs
  node/src/chain_specs/manta.rs
  node/src/chain_specs/mod.rs
  runtime/calamari/Cargo.toml
  runtime/calamari/src/fee.rs
  runtime/calamari/src/impls.rs
  runtime/calamari/tests/common/mock.rs
  runtime/calamari/tests/common/mod.rs
  runtime/calamari/tests/integration_tests.rs
  runtime/primitives/src/helpers.rs
  runtime/primitives/src/lib.rs
Labels: Test-Automation, Runtime

#426 [MANTA]: DCO for community PRs
  .github/workflows/dco.yml
Labels: DevOps, CI/CD

#421 [manta] Fix CI integration test false negatives
  .github/workflows/publish-draft-releases.yml
Labels: Test-Automation, CI/CD

#393 [manta] CI runtime upgrade test and github templates improvements
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/publish-draft-releases.yml
Labels: CI/CD

#457 Add manual try-runtime test against Calamari mainnet
  .github/workflows/try-runtime-calamari-mainnet.yml
Labels: Test-Automation, CI/CD
